# Generated by Django 5.2.6 on 2026-08-19 20:17

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experience', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('type', models.CharField(choices=[('PROJECT', 'Project'), ('ARTICLE', 'Article'), ('DESIGN', 'Design'), ('CODE', 'Code repository'), ('VIDEO', 'Video'), ('OTHER', 'Other')], default='PROJECT', max_length=10)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio/items/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='portfolio/covers/', validators=[apps.common.validators.validate_image_upload])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='experience.experience')),
                ('skills', models.ManyToManyField(blank=True, related_name='portfolio_items', to='taxonomy.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cv_portfolio_item',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_slug', models.SlugField(max_length=64, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('visible_blocks', models.JSONField(blank=True, default=dict)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cv_public_profile',
            },
        ),
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='My CV', max_length=160)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('template', models.CharField(choices=[('CLASSIC', 'Classic'), ('MODERN', 'Modern'), ('COMPACT', 'Compact')], default='MODERN', max_length=10)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True, max_length=2000)),
                ('sections_config', models.JSONField(blank=True, default=list)),
                ('is_primary', models.BooleanField(default=False)),
                ('target_profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvs', to='taxonomy.profession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cv_document',
                'ordering': ['-is_primary', '-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='one_primary_cv_per_user')],
            },
        ),
    ]
