# Generated by Django 5.2.17 on 2026-09-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='quality_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='quality_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='quality_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
