# Generated by Django 5.2.17 on 2026-09-17 17:18

import apps.common.storage
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cvdocument_quality_breakdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=apps.common.storage.PrivateMediaStorage(), upload_to=apps.common.storage.portfolio_cover_path, validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='file',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateMediaStorage(), upload_to=apps.common.storage.portfolio_item_path),
        ),
    ]
