# Generated by Django 5.2.6 on 2026-08-19 20:17

import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(blank=True, max_length=120)),
                ('field_of_study', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_education',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=32)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('size', models.CharField(choices=[('MICRO', '1-9'), ('SMALL', '10-49'), ('MEDIUM', '50-249'), ('LARGE', '250+')], default='SMALL', max_length=8)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', validators=[apps.common.validators.validate_image_upload])),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='taxonomy.region')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_employers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_employer',
            },
        ),
        migrations.CreateModel(
            name='EmployerMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('RECRUITER', 'Recruiter'), ('TRAINER', 'Trainer')], default='RECRUITER', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_roles', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='profiles.employerprofile')),
            ],
            options={
                'db_table': 'profiles_employer_member',
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, max_length=4000)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/mentors/', validators=[apps.common.validators.validate_image_upload])),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('is_free', models.BooleanField(default=True)),
                ('hourly_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('sessions_count', models.PositiveIntegerField(default=0)),
                ('accepting_students', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('expertise', models.ManyToManyField(blank=True, related_name='mentors', to='taxonomy.skill')),
                ('professions', models.ManyToManyField(blank=True, related_name='mentors', to='taxonomy.profession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_mentor',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youth_id', models.CharField(db_index=True, max_length=24, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNDISCLOSED', 'Prefer not to say')], default='UNDISCLOSED', max_length=12)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/students/', validators=[apps.common.validators.validate_image_upload])),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('education_status', models.CharField(choices=[('SCHOOL', 'School student'), ('COLLEGE', 'College / lyceum'), ('UNIVERSITY', 'University student'), ('GRADUATE', 'Graduate'), ('NONE', 'Not studying')], default='NONE', max_length=16)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('study_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('STUDYING', 'Studying'), ('LOOKING', 'Looking for work'), ('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-employed / entrepreneur'), ('NOT_LOOKING', 'Not looking')], default='STUDYING', max_length=16)),
                ('open_to_work', models.BooleanField(default=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('profile_completion', models.PositiveSmallIntegerField(default=0)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('diagnostics_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_high_potential', models.BooleanField(default=False)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='taxonomy.region')),
                ('target_profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeting_students', to='taxonomy.profession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_student',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('status', models.CharField(choices=[('DECLARED', 'Declared'), ('VERIFIED', 'Verified')], default='DECLARED', max_length=10)),
                ('best_source', models.CharField(choices=[('SELF', 'Self-declared'), ('COURSE', 'Course completion'), ('EXPERIENCE', 'Work experience'), ('MENTOR', 'Mentor assessment'), ('TEST', 'Test result'), ('EMPLOYER', 'Employer verification')], default='SELF', max_length=12)),
                ('last_evidence_at', models.DateTimeField(blank=True, null=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='taxonomy.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_user_skill',
                'ordering': ['-proficiency'],
            },
        ),
        migrations.CreateModel(
            name='SkillEvidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('SELF', 'Self-declared'), ('COURSE', 'Course completion'), ('EXPERIENCE', 'Work experience'), ('MENTOR', 'Mentor assessment'), ('TEST', 'Test result'), ('EMPLOYER', 'Employer verification')], max_length=12)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0.35, max_digits=3)),
                ('ref_type', models.CharField(blank=True, max_length=40)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_skill_evidence', to=settings.AUTH_USER_MODEL)),
                ('user_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='profiles.userskill')),
            ],
            options={
                'db_table': 'profiles_skill_evidence',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['verification_status', 'is_active'], name='profiles_em_verific_9f43fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='employermember',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_employer_member'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['verification_status', 'accepting_students'], name='profiles_me_verific_34ebed_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['region'], name='profiles_st_region__6b28ae_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['target_profession'], name='profiles_st_target__fa9a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['open_to_work', 'employment_status'], name='profiles_st_open_to_6579d3_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['skill', 'status'], name='profiles_us_skill_i_dd6104_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['user', 'status'], name='profiles_us_user_id_580300_idx'),
        ),
        migrations.AddConstraint(
            model_name='userskill',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='uniq_user_skill'),
        ),
        migrations.AddConstraint(
            model_name='userskill',
            constraint=models.CheckConstraint(condition=models.Q(('proficiency__gte', 0), ('proficiency__lte', 100)), name='user_skill_proficiency_range'),
        ),
        migrations.AddIndex(
            model_name='skillevidence',
            index=models.Index(fields=['user_skill', 'issued_at'], name='profiles_sk_user_sk_61ffd0_idx'),
        ),
        migrations.AddIndex(
            model_name='skillevidence',
            index=models.Index(fields=['ref_type', 'ref_id'], name='profiles_sk_ref_typ_9c7e39_idx'),
        ),
    ]
