# Generated by Django 5.2.17 on 2026-09-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_studentprofile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillevidence',
            name='source',
            field=models.CharField(choices=[('SELF', 'Self-declared'), ('SOFT_TEST', 'Soft skills assessment'), ('COURSE', 'Course completion'), ('EXPERIENCE', 'Work experience'), ('MENTOR', 'Mentor assessment'), ('TEST', 'Test result'), ('EMPLOYER', 'Employer verification')], max_length=12),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='best_source',
            field=models.CharField(choices=[('SELF', 'Self-declared'), ('SOFT_TEST', 'Soft skills assessment'), ('COURSE', 'Course completion'), ('EXPERIENCE', 'Work experience'), ('MENTOR', 'Mentor assessment'), ('TEST', 'Test result'), ('EMPLOYER', 'Employer verification')], default='SELF', max_length=12),
        ),
    ]
