# Generated by Django 5.2.17 on 2026-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # 0004 clears the rows holding 'MENTOR' and drops the mentorship
        # tables. A `choices` change is metadata only in PostgreSQL, so
        # running this first would leave that data behind as strings the
        # application can no longer interpret — and the DeleteModel below
        # would fail on the foreign key from mentorship_session anyway.
        ('profiles', '0004_retire_mentorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillevidence',
            name='source',
            field=models.CharField(choices=[('SELF', 'Self-declared'), ('SOFT_TEST', 'Soft skills assessment'), ('COURSE', 'Course completion'), ('EXPERIENCE', 'Work experience'), ('TEST', 'Test result'), ('EMPLOYER', 'Employer verification')], max_length=12),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='best_source',
            field=models.CharField(choices=[('SELF', 'Self-declared'), ('SOFT_TEST', 'Soft skills assessment'), ('COURSE', 'Course completion'), ('EXPERIENCE', 'Work experience'), ('TEST', 'Test result'), ('EMPLOYER', 'Employer verification')], default='SELF', max_length=12),
        ),
        migrations.DeleteModel(
            name='MentorProfile',
        ),
    ]
