# Generated by Django 5.2.17 on 2026-09-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_drop_mentor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
