# Generated by Django 5.2.17 on 2026-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('EMPLOYER', 'Employer'), ('ADMIN', 'Administrator')], default='STUDENT', max_length=16),
        ),
    ]
