# Generated by Django 5.2.17 on 2026-09-17 16:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('browser', models.CharField(blank=True, max_length=40)),
                ('system', models.CharField(blank=True, max_length=40)),
                ('kind', models.CharField(blank=True, max_length=16)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_login_device',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', '-last_seen_at'], name='accounts_lo_user_id_da78af_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'fingerprint'), name='uniq_login_device_user_print')],
            },
        ),
    ]
