# Generated by Django 5.2.6 on 2026-08-21 07:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('EMPLOYER', 'Employer'), ('MENTOR', 'Mentor'), ('ADMIN', 'Administrator')], db_index=True, max_length=16)),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=16)),
                ('price_minor', models.PositiveIntegerField(default=0, help_text='Price in minor units, e.g. 149000 means 1 490.00 for a 2-exponent currency.')),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField(default=2)),
                ('interval', models.CharField(choices=[('MONTH', 'Monthly'), ('YEAR', 'Yearly'), ('NONE', 'No recurring charge')], default='MONTH', max_length=8)),
                ('trial_days', models.PositiveSmallIntegerField(default=0)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Assigned automatically on registration for this role.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('role', 'sort_order', 'price_minor'),
                'indexes': [models.Index(fields=['role', 'is_active'], name='billing_pla_role_8bd433_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('role',), name='billing_one_default_plan_per_role')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=16)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(default='manual', max_length=32)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=128)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=16)),
                ('provider', models.CharField(default='manual', max_length=32)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=128)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.plan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.subscription')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(db_index=True, max_length=48)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('used', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'feature', 'period_start'], name='billing_fea_user_id_cb0ec2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'feature', 'period_start'), name='billing_usage_unique_per_period')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='billing_sub_status_684a21_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='billing_pay_user_id_c9be81_idx'),
        ),
    ]
