# Generated by Django 5.2.17 on 2026-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('EMPLOYER', 'Employer'), ('ADMIN', 'Administrator')], db_index=True, max_length=16),
        ),
    ]
