# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('profiles', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('SINGLE', 'Single choice'), ('MULTIPLE', 'Multiple choice'), ('TRUE_FALSE', 'True / false'), ('SHORT_ANSWER', 'Short answer')], default='SINGLE', max_length=14)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('accepted_answers', models.JSONField(blank=True, default=list)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='taxonomy.skill')),
            ],
            options={
                'db_table': 'assessment_question',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessment.question')),
            ],
            options={
                'db_table': 'assessment_answer_option',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('type', models.CharField(choices=[('COURSE_TEST', 'Course test'), ('SKILL_TEST', 'Standalone skill test'), ('DIAGNOSTIC', 'Onboarding diagnostic'), ('SCREENING', 'Employer screening')], default='SKILL_TEST', max_length=12)),
                ('passing_score', models.PositiveSmallIntegerField(default=60)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=30)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('show_correct_answers', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('moderation_note', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_tests', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='learning.course')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='profiles.employerprofile')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.test'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired'), ('GRADED', 'Graded')], default='IN_PROGRESS', max_length=12)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('max_score', models.PositiveSmallIntegerField(default=0)),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_test_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.CharField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.PositiveSmallIntegerField(default=0)),
                ('selected_options', models.ManyToManyField(blank=True, to='assessment.answeroption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='assessment.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.testattempt')),
            ],
            options={
                'db_table': 'assessment_attempt_answer',
            },
        ),
        migrations.CreateModel(
            name='TestSkill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_links', to='taxonomy.skill')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='assessment.test')),
            ],
            options={
                'db_table': 'assessment_test_skill',
            },
        ),
        migrations.CreateModel(
            name='TestSkillResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('questions_total', models.PositiveSmallIntegerField(default=0)),
                ('questions_correct', models.PositiveSmallIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_results', to='assessment.testattempt')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='taxonomy.skill')),
            ],
            options={
                'db_table': 'assessment_test_skill_result',
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['status', 'type'], name='assessment__status_4a60ba_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['employer', 'status'], name='assessment__employe_484aba_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'passed'], name='assessment__test_id_2120a5_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test'], name='assessment__user_id_94480d_idx'),
        ),
        migrations.AddConstraint(
            model_name='testattempt',
            constraint=models.UniqueConstraint(fields=('user', 'test', 'attempt_no'), name='uniq_test_attempt'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_attempt_answer'),
        ),
        migrations.AddConstraint(
            model_name='testskill',
            constraint=models.UniqueConstraint(fields=('test', 'skill'), name='uniq_test_skill'),
        ),
        migrations.AddConstraint(
            model_name='testskillresult',
            constraint=models.UniqueConstraint(fields=('attempt', 'skill'), name='uniq_attempt_skill_result'),
        ),
    ]
