# Generated by Django 5.2.17 on 2026-09-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SINGLE', 'Single choice'), ('MULTIPLE', 'Multiple choice'), ('TRUE_FALSE', 'True / false'), ('SHORT_ANSWER', 'Short answer'), ('SITUATIONAL', 'Situational judgement')], default='SINGLE', max_length=14),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('COURSE_TEST', 'Course test'), ('SKILL_TEST', 'Standalone skill test'), ('DIAGNOSTIC', 'Onboarding diagnostic'), ('SCREENING', 'Employer screening'), ('SOFT_SKILL', 'Soft skills assessment')], default='SKILL_TEST', max_length=12),
        ),
    ]
