# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('cv', '0001_initial'),
        ('profiles', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(blank=True, max_length=4000)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=14)),
                ('match_score_at_apply', models.PositiveSmallIntegerField(default=0)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('employer_note', models.TextField(blank=True)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='cv.cvdocument')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=14)),
                ('to_status', models.CharField(max_length=14)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.application')),
            ],
            options={
                'db_table': 'jobs_application_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('ONSITE', 'On site'), ('PHONE', 'Phone')], default='ONLINE', max_length=8)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='SCHEDULED', max_length=10)),
                ('feedback', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.application')),
            ],
            options={
                'db_table': 'jobs_interview',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('INTERNSHIP', 'Internship'), ('CONTRACT', 'Contract'), ('FREELANCE', 'Freelance')], default='FULL_TIME', max_length=12)),
                ('work_mode', models.CharField(choices=[('ONSITE', 'On site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=8)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('min_experience_months', models.PositiveSmallIntegerField(default=0)),
                ('education_required', models.CharField(choices=[('NONE', 'No requirement'), ('SCHOOL', 'Secondary school'), ('COLLEGE', 'College / lyceum'), ('UNIVERSITY', 'University degree')], default='NONE', max_length=12)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('is_salary_public', models.BooleanField(default=True)),
                ('positions_count', models.PositiveSmallIntegerField(default=1)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('moderation_note', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='profiles.employerprofile')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_vacancies', to=settings.AUTH_USER_MODEL)),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='taxonomy.profession')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='taxonomy.region')),
            ],
            options={
                'verbose_name_plural': 'vacancies',
                'db_table': 'jobs_vacancy',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedVacancy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_vacancies', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.vacancy')),
            ],
            options={
                'db_table': 'jobs_saved_vacancy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=8)),
                ('retention_30', models.BooleanField(blank=True, null=True)),
                ('retention_90', models.BooleanField(blank=True, null=True)),
                ('retention_180', models.BooleanField(blank=True, null=True)),
                ('income_reported', models.PositiveIntegerField(blank=True, null=True)),
                ('income_currency', models.CharField(default='UZS', max_length=3)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement', to='jobs.application')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_placements', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='profiles.employerprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='jobs.vacancy')),
            ],
            options={
                'db_table': 'jobs_placement',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='jobs.vacancy'),
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement', models.CharField(choices=[('REQUIRED', 'Required'), ('PREFERRED', 'Preferred')], default='REQUIRED', max_length=12)),
                ('min_knowledge_score', models.PositiveSmallIntegerField(default=50)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancy_links', to='taxonomy.skill')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='jobs.vacancy')),
            ],
            options={
                'db_table': 'jobs_vacancy_skill',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VacancyTest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='assessment.test')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_tests', to='jobs.vacancy')),
            ],
            options={
                'db_table': 'jobs_vacancy_test',
            },
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['status', '-published_at'], name='jobs_vacanc_status_72d032_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['employer', 'status'], name='jobs_vacanc_employe_11a4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['region', 'status'], name='jobs_vacanc_region__d0a73c_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['profession', 'status'], name='jobs_vacanc_profess_444b48_idx'),
        ),
        migrations.AddConstraint(
            model_name='vacancy',
            constraint=models.CheckConstraint(condition=models.Q(('salary_max__isnull', True), ('salary_min__isnull', True), ('salary_max__gte', models.F('salary_min')), _connector='OR'), name='vacancy_salary_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='savedvacancy',
            constraint=models.UniqueConstraint(fields=('user', 'vacancy'), name='uniq_saved_vacancy'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['student', 'status'], name='jobs_placem_student_7488be_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['employer', 'status'], name='jobs_placem_employe_d7b1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['start_date'], name='jobs_placem_start_d_d393ad_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['vacancy', 'status'], name='jobs_applic_vacancy_08d434_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student', 'status'], name='jobs_applic_student_09cda8_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'vacancy'), name='uniq_application_per_vacancy'),
        ),
        migrations.AddIndex(
            model_name='vacancyskill',
            index=models.Index(fields=['skill', 'requirement'], name='jobs_vacanc_skill_i_670bee_idx'),
        ),
        migrations.AddConstraint(
            model_name='vacancyskill',
            constraint=models.UniqueConstraint(fields=('vacancy', 'skill'), name='uniq_vacancy_skill'),
        ),
        migrations.AddConstraint(
            model_name='vacancytest',
            constraint=models.UniqueConstraint(fields=('vacancy', 'test'), name='uniq_vacancy_test'),
        ),
    ]
