# Generated by Django 5.2.17 on 2026-08-27 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInvite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('proposed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('ONSITE', 'On site'), ('PHONE', 'Phone')], default='ONLINE', max_length=8)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for a reply'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled by the employer')], default='PENDING', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True, max_length=1000)),
                ('match_score_at_invite', models.PositiveSmallIntegerField(default=0)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_interview_invites', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_invites', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_invites', to='jobs.vacancy')),
            ],
            options={
                'db_table': 'jobs_interview_invite',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='jobs_interv_student_3e3799_idx'), models.Index(fields=['vacancy', 'status'], name='jobs_interv_vacancy_4b6290_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('vacancy', 'student'), name='uniq_pending_invite_per_vacancy')],
            },
        ),
    ]
