# Generated by Django 5.2.6 on 2026-08-24 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_imports', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'learning_content_provider',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='translation_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ContentImport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(help_text='File name or endpoint.', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('PARTIAL', 'Completed with errors'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('courses_created', models.PositiveIntegerField(default=0)),
                ('courses_updated', models.PositiveIntegerField(default=0)),
                ('lessons_written', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='learning.contentprovider')),
            ],
            options={
                'db_table': 'learning_content_import',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='learning.contentprovider'),
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PDF', 'PDF'), ('SLIDES', 'Slides'), ('WORKSHEET', 'Worksheet'), ('DATASET', 'Dataset'), ('CODE', 'Code'), ('LINK', 'External link'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=800)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=2)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='learning.lesson')),
            ],
            options={
                'db_table': 'learning_lesson_attachment',
                'ordering': ('order', 'title'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('lesson', 'external_id'), name='learning_attachment_unique_external')],
            },
        ),
    ]
