# Generated by Django 5.2.17 on 2026-08-27 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_lessonnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('FILE', 'File'), ('LINK', 'Link'), ('BOOK', 'Book')], default='LINK', max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='course-materials/')),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.lesson')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_course_material',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['course', 'lesson'], name='learning_co_course__e50846_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), ('kind', 'FILE')), ('kind__in', ['LINK', 'BOOK']), _connector='OR'), name='material_file_kind_has_a_file')],
            },
        ),
    ]
