# Generated by Django 5.2.17 on 2026-08-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_lesson_transcript_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='recap',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recap_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recap_source_hash',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
