# Generated by Django 5.2.17 on 2026-08-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_lesson_recap_lesson_recap_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='check_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='check_source_hash',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='check_answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='check_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='check_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
