# Generated by Django 5.2.17 on 2026-09-08 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_lesson_check_questions_lesson_check_source_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursematerial',
            name='material_file_kind_has_a_file',
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='kind',
            field=models.CharField(choices=[('FILE', 'File'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('LINK', 'Link'), ('BOOK', 'Book')], default='LINK', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='coursematerial',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), ('kind__in', ['FILE', 'IMAGE'])), ('kind__in', ['VIDEO', 'LINK', 'BOOK']), _connector='OR'), name='material_file_kind_has_a_file'),
        ),
    ]
