# Generated by Django 5.2.17 on 2026-09-08 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_material_video_and_image_kinds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonQuiz',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions', models.JSONField(default=list)),
                ('source_hash', models.CharField(max_length=32)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_quizzes', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_lesson_quiz',
                'indexes': [models.Index(fields=['user', 'lesson'], name='learning_le_user_id_3e046a_idx')],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'user'), name='uniq_lesson_quiz_per_user')],
            },
        ),
    ]
