# Generated by Django 5.2.17 on 2026-09-17 17:18

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_lesson_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateMediaStorage(), upload_to=apps.common.storage.certificate_path),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateMediaStorage(), upload_to=apps.common.storage.course_material_path),
        ),
    ]
