# Generated by Django 5.2.17 on 2026-09-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_move_private_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
