# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalIndex',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_indexes', to='taxonomy.capitaldimension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_indexes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capital_index',
                'ordering': ['dimension__order'],
                'constraints': [models.UniqueConstraint(fields=('user', 'dimension'), name='uniq_capital_user_dimension'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='capital_score_range')],
            },
        ),
        migrations.CreateModel(
            name='CapitalSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('taken_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='taxonomy.capitaldimension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capital_snapshot',
                'ordering': ['taken_at'],
                'indexes': [models.Index(fields=['user', 'taken_at'], name='capital_sna_user_id_15d0c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CapitalWeightConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('weights', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capital_weight_config',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_capital_config')],
            },
        ),
    ]
