# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('weights', models.JSONField(default=dict, help_text='e.g. {"test": 0.5, "course": 0.25, "experience": 0.15, "mentor": 0.1}')),
                ('decay_half_life_days', models.PositiveSmallIntegerField(default=540)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_config',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_knowledge_config')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('evidence_count', models.PositiveSmallIntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_scores', to='taxonomy.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_score',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['user', '-score'], name='knowledge_s_user_id_a54132_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'skill'), name='uniq_knowledge_user_skill'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='knowledge_score_range')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('taken_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_snapshots', to='taxonomy.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_snapshot',
                'ordering': ['taken_at'],
                'indexes': [models.Index(fields=['user', 'skill', 'taken_at'], name='knowledge_s_user_id_decf57_idx')],
            },
        ),
    ]
