# Generated by Django 5.2.17 on 2026-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeconfig',
            name='weights',
            field=models.JSONField(default=dict, help_text='e.g. {"test": 0.6, "course": 0.25, "experience": 0.15}'),
        ),
    ]
