# Generated by Django 5.2.17 on 2026-09-04 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('audience_roles', models.JSONField(blank=True, default=list)),
                ('min_account_age_days', models.PositiveSmallIntegerField(default=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RUNNING', 'Running'), ('FINISHED', 'Finished')], default='DRAFT', max_length=8)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('invited_count', models.PositiveIntegerField(default=0)),
                ('responded_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_review_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('CAMPAIGN', 'Admin campaign'), ('COURSE_COMPLETED', 'Finished a course'), ('PLACEMENT', 'Started a job through the platform'), ('MENTOR_SESSION', 'Completed a mentor session'), ('HIRED_CANDIDATE', 'Hired through the platform'), ('MANUAL', 'Wrote a review unprompted')], default='CAMPAIGN', max_length=18)),
                ('ref_type', models.CharField(blank=True, max_length=40)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='feedback.reviewcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_review_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_at_review', models.CharField(choices=[('STUDENT', 'Student'), ('EMPLOYER', 'Employer'), ('MENTOR', 'Mentor'), ('ADMIN', 'Administrator')], max_length=16)),
                ('trigger', models.CharField(choices=[('CAMPAIGN', 'Admin campaign'), ('COURSE_COMPLETED', 'Finished a course'), ('PLACEMENT', 'Started a job through the platform'), ('MENTOR_SESSION', 'Completed a mentor session'), ('HIRED_CANDIDATE', 'Hired through the platform'), ('MANUAL', 'Wrote a review unprompted')], default='MANUAL', max_length=18)),
                ('rating', models.PositiveSmallIntegerField()),
                ('nps_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pros', models.TextField(blank=True, max_length=2000)),
                ('cons', models.TextField(blank=True, max_length=2000)),
                ('suggestion', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING_REVIEW', max_length=16)),
                ('moderation_note', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('admin_response', models.TextField(blank=True, max_length=2000)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_reviews', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='feedback.reviewcampaign')),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='feedback.reviewrequest')),
            ],
            options={
                'db_table': 'feedback_platform_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['user', 'responded_at'], name='feedback_re_user_id_e44257_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['campaign', 'responded_at'], name='feedback_re_campaig_05080a_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign__isnull', False)), fields=('user', 'campaign'), name='uniq_campaign_request_per_user'),
        ),
        migrations.AddIndex(
            model_name='platformreview',
            index=models.Index(fields=['role_at_review', '-created_at'], name='feedback_pl_role_at_8b6ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='platformreview',
            index=models.Index(fields=['status', '-created_at'], name='feedback_pl_status_232767_idx'),
        ),
        migrations.AddIndex(
            model_name='platformreview',
            index=models.Index(fields=['rating'], name='feedback_pl_rating_38c071_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformreview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='platform_review_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='platformreview',
            constraint=models.CheckConstraint(condition=models.Q(('nps_score__isnull', True), models.Q(('nps_score__gte', 0), ('nps_score__lte', 10)), _connector='OR'), name='platform_review_nps_range'),
        ),
    ]
