# Generated by Django 5.2.17 on 2026-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformreview',
            name='role_at_review',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('EMPLOYER', 'Employer'), ('ADMIN', 'Administrator')], max_length=16),
        ),
        migrations.AlterField(
            model_name='platformreview',
            name='trigger',
            field=models.CharField(choices=[('CAMPAIGN', 'Admin campaign'), ('COURSE_COMPLETED', 'Finished a course'), ('PLACEMENT', 'Started a job through the platform'), ('HIRED_CANDIDATE', 'Hired through the platform'), ('MANUAL', 'Wrote a review unprompted')], default='MANUAL', max_length=18),
        ),
        migrations.AlterField(
            model_name='reviewrequest',
            name='trigger',
            field=models.CharField(choices=[('CAMPAIGN', 'Admin campaign'), ('COURSE_COMPLETED', 'Finished a course'), ('PLACEMENT', 'Started a job through the platform'), ('HIRED_CANDIDATE', 'Hired through the platform'), ('MANUAL', 'Wrote a review unprompted')], default='CAMPAIGN', max_length=18),
        ),
    ]
