# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchWeightProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('version', models.CharField(default='1.0', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('weights', models.JSONField(default=dict)),
                ('min_score_to_notify', models.PositiveSmallIntegerField(default=70)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_weight_profile',
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('coverage_score', models.PositiveSmallIntegerField(default=0)),
                ('knowledge_score', models.PositiveSmallIntegerField(default=0)),
                ('verification_score', models.PositiveSmallIntegerField(default=0)),
                ('experience_score', models.PositiveSmallIntegerField(default=0)),
                ('education_score', models.PositiveSmallIntegerField(default=0)),
                ('location_score', models.PositiveSmallIntegerField(default=0)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('explanation', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('is_stale', models.BooleanField(db_index=True, default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='jobs.vacancy')),
                ('weight_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='matching.matchweightprofile')),
            ],
            options={
                'db_table': 'matching_result',
            },
        ),
        migrations.CreateModel(
            name='ProfessionMatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_matches', to='taxonomy.profession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_profession_match',
            },
        ),
        migrations.AddConstraint(
            model_name='matchweightprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_match_profile'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['vacancy', '-overall_score'], name='matching_re_vacancy_287bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['student', '-overall_score'], name='matching_re_student_1c1c16_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchresult',
            constraint=models.UniqueConstraint(fields=('student', 'vacancy'), name='uniq_match_student_vacancy'),
        ),
        migrations.AddConstraint(
            model_name='matchresult',
            constraint=models.CheckConstraint(condition=models.Q(('overall_score__gte', 0), ('overall_score__lte', 100)), name='match_overall_score_range'),
        ),
        migrations.AddIndex(
            model_name='professionmatch',
            index=models.Index(fields=['student', '-score'], name='matching_pr_student_ddcada_idx'),
        ),
        migrations.AddConstraint(
            model_name='professionmatch',
            constraint=models.UniqueConstraint(fields=('student', 'profession'), name='uniq_profession_match'),
        ),
    ]
