# Generated by Django 5.2.17 on 2026-09-09 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_interviewinvite'),
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='relevance_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='relevance_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='relevance_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['student', '-relevance_score', '-overall_score'], name='matching_re_student_cdfc09_idx'),
        ),
    ]
