# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('WORK', 'Work experience'), ('FREELANCE', 'Freelance'), ('VOLUNTEER', 'Volunteering'), ('PROJECT', 'Project'), ('COMPETITION', 'Competition'), ('HACKATHON', 'Hackathon'), ('ACHIEVEMENT', 'Achievement')], default='WORK', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('url', models.URLField(blank=True)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experience_entry',
                'ordering': ['-is_current', '-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceSkill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='experience.experience')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_links', to='taxonomy.skill')),
            ],
            options={
                'db_table': 'experience_skill',
            },
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('FILE', 'File'), ('LINK', 'Link'), ('VIDEO', 'Video')], default='LINK', max_length=8)),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio/')),
                ('url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='experience.experience')),
            ],
            options={
                'db_table': 'experience_project_asset',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['user', 'type'], name='experience__user_id_2f5bca_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['user', '-start_date'], name='experience__user_id_8bb8e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='experience_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='experienceskill',
            constraint=models.UniqueConstraint(fields=('experience', 'skill'), name='uniq_experience_skill'),
        ),
    ]
