# Generated by Django 5.2.17 on 2026-09-17 17:18

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectasset',
            name='file',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateMediaStorage(), upload_to=apps.common.storage.experience_asset_path),
        ),
    ]
