# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(choices=[('RULE_BASED', 'Rule based (no external calls)'), ('ANTHROPIC', 'Anthropic'), ('OPENAI', 'OpenAI'), ('CUSTOM', 'Custom endpoint')], default='RULE_BASED', max_length=16)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('api_key_env_name', models.CharField(blank=True, help_text='Name of the environment variable holding the key, e.g. ANTHROPIC_API_KEY.', max_length=64)),
                ('endpoint', models.URLField(blank=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('max_tokens', models.PositiveIntegerField(default=2048)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('monthly_budget', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_provider_config',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_ai_provider')],
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('use_case', models.CharField(choices=[('CAREER', 'Career guidance'), ('LEARNING', 'Learning recommendations'), ('SKILL_GAP', 'Skill gap analysis'), ('PLAN', 'Development plan generation'), ('CV', 'CV assistance'), ('MATCH_EXPLAIN', 'Match explanation'), ('COACH', 'Coaching conversation')], max_length=16)),
                ('provider', models.CharField(choices=[('RULE_BASED', 'Rule based (no external calls)'), ('ANTHROPIC', 'Anthropic'), ('OPENAI', 'OpenAI'), ('CUSTOM', 'Custom endpoint')], max_length=16)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('input_preview', models.TextField(blank=True)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('BLOCKED', 'Blocked by safety filter'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout')], default='SUCCESS', max_length=8)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_request_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('COURSE', 'Course'), ('VACANCY', 'Vacancy'), ('SKILL', 'Skill'), ('MENTOR', 'Mentor'), ('TASK', 'Task'), ('PROFESSION', 'Profession'), ('TEST', 'Test')], max_length=12)),
                ('ref_type', models.CharField(blank=True, max_length=40)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('reason_text', models.TextField(blank=True)),
                ('reason_data', models.JSONField(blank=True, default=dict)),
                ('use_case', models.CharField(choices=[('CAREER', 'Career guidance'), ('LEARNING', 'Learning recommendations'), ('SKILL_GAP', 'Skill gap analysis'), ('PLAN', 'Development plan generation'), ('CV', 'CV assistance'), ('MATCH_EXPLAIN', 'Match explanation'), ('COACH', 'Coaching conversation')], default='LEARNING', max_length=16)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SEEN', 'Seen'), ('ACCEPTED', 'Accepted'), ('DISMISSED', 'Dismissed')], default='NEW', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='ai.airequestlog')),
            ],
            options={
                'db_table': 'ai_recommendation',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISafetyEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=8)),
                ('action', models.CharField(choices=[('BLOCKED', 'Blocked'), ('REDACTED', 'Redacted'), ('ESCALATED', 'Escalated to a human specialist')], max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_events', to='ai.airequestlog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_safety_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_safety_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('UP', 'Helpful'), ('DOWN', 'Not helpful')], max_length=4)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai.airecommendation')),
            ],
            options={
                'db_table': 'ai_feedback',
                'constraints': [models.UniqueConstraint(fields=('recommendation', 'user'), name='uniq_ai_feedback')],
            },
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['use_case', '-created_at'], name='ai_request__use_cas_65146c_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['status', '-created_at'], name='ai_request__status_b1456e_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['user', 'type', 'status'], name='ai_recommen_user_id_ef2fbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='airecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'type', 'ref_id'), name='uniq_recommendation_per_target'),
        ),
        migrations.AddIndex(
            model_name='aisafetyevent',
            index=models.Index(fields=['rule', '-created_at'], name='ai_safety_e_rule_d93d60_idx'),
        ),
    ]
