# Generated by Django 5.2.6 on 2026-08-21 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], db_index=True, default='IN_PROGRESS', max_length=16)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('applied', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(default='RULE_BASED', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_intake_session',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='ai_intake_s_user_id_098a3e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('user',), name='ai_one_active_intake_per_user')],
            },
        ),
    ]
