# Generated by Django 5.2.6 on 2026-08-22 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_intakesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant')], max_length=10)),
                ('text', models.TextField(blank=True, max_length=4000)),
                ('code', models.CharField(blank=True, max_length=48)),
                ('intent', models.CharField(blank=True, max_length=32)),
                ('grounding', models.JSONField(blank=True, default=dict)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('blocked', models.BooleanField(default=False)),
                ('block_rule', models.CharField(blank=True, max_length=64)),
                ('provider', models.CharField(default='RULE_BASED', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_chat_message',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_chat_mes_user_id_854433_idx')],
            },
        ),
    ]
