# Generated by Django 5.2.6 on 2026-08-23 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_chatthread_chatmessage_thread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='last_message_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
