# Generated by Django 5.2.17 on 2026-08-28 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_chatthread_last_message_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aisafetyevent',
            name='review_note',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='aisafetyevent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aisafetyevent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_safety_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aisafetyevent',
            index=models.Index(fields=['reviewed_at', 'severity', '-created_at'], name='ai_safety_e_reviewe_bef07b_idx'),
        ),
    ]
