# Generated by Django 5.2.17 on 2026-09-08 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_aisafetyevent_review_note_aisafetyevent_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail', models.CharField(blank=True, choices=[('BRIEF', 'Short'), ('NORMAL', 'Normal'), ('DETAILED', 'Detailed')], default='', max_length=8)),
                ('tone', models.CharField(blank=True, choices=[('WARM', 'Encouraging'), ('NEUTRAL', 'Neutral'), ('DIRECT', 'Direct')], default='', max_length=8)),
                ('explain_terms', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_assistant_profile',
            },
        ),
    ]
