# Generated by Django 5.2.17 on 2026-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_assistant_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecommendation',
            name='type',
            field=models.CharField(choices=[('COURSE', 'Course'), ('VACANCY', 'Vacancy'), ('SKILL', 'Skill'), ('TASK', 'Task'), ('PROFESSION', 'Profession'), ('TEST', 'Test')], max_length=12),
        ),
    ]
