# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('actor_role', models.CharField(blank=True, max_length=16)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Failed login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password change'), ('ROLE_CHANGE', 'Role change'), ('MODERATE', 'Moderation decision'), ('STATUS_CHANGE', 'Status change'), ('CONSENT_GRANT', 'Consent granted'), ('CONSENT_REVOKE', 'Consent revoked'), ('PII_ACCESS', 'Personal data accessed'), ('EXPORT', 'Data export'), ('CONFIG_CHANGE', 'Configuration change')], max_length=20)),
                ('object_type', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('NOTICE', 'Notice'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=8)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_log_object__8ccc11_idx'), models.Index(fields=['actor', '-created_at'], name='audit_log_actor_i_91cd96_idx'), models.Index(fields=['action', '-created_at'], name='audit_log_action_7c9e02_idx'), models.Index(fields=['severity', '-created_at'], name='audit_log_severit_6f4f31_idx')],
            },
        ),
    ]
