# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('key', models.CharField(max_length=64)),
                ('dimension_key', models.CharField(blank=True, max_length=32)),
                ('dimension_value', models.CharField(blank=True, max_length=64)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'analytics_daily_metric',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['key', '-date'], name='analytics_d_key_cebd3c_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'key', 'dimension_key', 'dimension_value'), name='uniq_daily_metric')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(choices=[('signed_up', 'Signed up'), ('onboarding_completed', 'Onboarding completed'), ('diagnostic_completed', 'Diagnostic completed'), ('profession_selected', 'Profession selected'), ('plan_generated', 'Development plan generated'), ('plan_activated', 'Development plan activated'), ('task_completed', 'Task completed'), ('course_enrolled', 'Course enrolled'), ('lesson_completed', 'Lesson completed'), ('course_completed', 'Course completed'), ('test_started', 'Test started'), ('test_submitted', 'Test submitted'), ('skill_verified', 'Skill verified'), ('experience_added', 'Experience added'), ('cv_created', 'CV created'), ('vacancy_viewed', 'Vacancy viewed'), ('application_submitted', 'Application submitted'), ('application_status_changed', 'Application status changed'), ('interview_scheduled', 'Interview scheduled'), ('hired', 'Hired'), ('mentor_session_requested', 'Mentor session requested'), ('mentor_session_completed', 'Mentor session completed'), ('recommendation_accepted', 'Recommendation accepted'), ('recommendation_dismissed', 'Recommendation dismissed')], max_length=48)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['name', '-occurred_at'], name='analytics_e_name_eeec35_idx'), models.Index(fields=['user', '-occurred_at'], name='analytics_e_user_id_7bd77b_idx')],
            },
        ),
    ]
