# Generated by Django 5.2.17 on 2026-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='name',
            field=models.CharField(choices=[('signed_up', 'Signed up'), ('onboarding_completed', 'Onboarding completed'), ('diagnostic_completed', 'Diagnostic completed'), ('profession_selected', 'Profession selected'), ('plan_generated', 'Development plan generated'), ('plan_activated', 'Development plan activated'), ('task_completed', 'Task completed'), ('course_enrolled', 'Course enrolled'), ('lesson_completed', 'Lesson completed'), ('course_completed', 'Course completed'), ('test_started', 'Test started'), ('test_submitted', 'Test submitted'), ('skill_verified', 'Skill verified'), ('experience_added', 'Experience added'), ('cv_created', 'CV created'), ('vacancy_viewed', 'Vacancy viewed'), ('application_submitted', 'Application submitted'), ('application_status_changed', 'Application status changed'), ('interview_scheduled', 'Interview scheduled'), ('hired', 'Hired'), ('recommendation_accepted', 'Recommendation accepted'), ('recommendation_dismissed', 'Recommendation dismissed')], max_length=48),
        ),
    ]
