# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idp', '0001_initial'),
        ('profiles', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('agenda', models.TextField(blank=True, max_length=2000)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('ONSITE', 'In person')], default='ONLINE', max_length=8)),
                ('meeting_link', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='REQUESTED', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('declined_reason', models.CharField(blank=True, max_length=255)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='profiles.mentorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentorship_session',
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_feedback', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='mentorship.mentorsession')),
            ],
            options={
                'db_table': 'mentorship_feedback',
            },
        ),
        migrations.CreateModel(
            name='MentorSkillAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=50)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to='mentorship.mentorfeedback')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assessments', to='taxonomy.skill')),
            ],
            options={
                'db_table': 'mentorship_skill_assessment',
            },
        ),
        migrations.AddField(
            model_name='mentorfeedback',
            name='skills_assessed',
            field=models.ManyToManyField(blank=True, through='mentorship.MentorSkillAssessment', to='taxonomy.skill'),
        ),
        migrations.CreateModel(
            name='PlanReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes requested')], default='PENDING', max_length=18)),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='idp.developmentplan')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentorship_plan_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['mentor', 'status'], name='mentorship__mentor__f34be7_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['student', 'status'], name='mentorship__student_99bb5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='mentorskillassessment',
            constraint=models.UniqueConstraint(fields=('feedback', 'skill'), name='uniq_mentor_skill_assessment'),
        ),
        migrations.AddConstraint(
            model_name='mentorfeedback',
            constraint=models.UniqueConstraint(fields=('session', 'author'), name='uniq_feedback_per_author'),
        ),
        migrations.AddConstraint(
            model_name='mentorfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='mentor_feedback_rating_range'),
        ),
    ]
