# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalDimension',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('slug', models.CharField(choices=[('KNOWLEDGE', 'Bilim kapitali'), ('PROFESSIONAL', 'Kasbiy kapital'), ('DIGITAL_AI', 'Raqamli va AI kapitali'), ('SOCIAL', 'Ijtimoiy kapital'), ('ENTREPRENEURIAL', 'Tadbirkorlik kapitali'), ('FINANCIAL', 'Moliyaviy kapital'), ('PERSONAL_ETHICAL', 'Shaxsiy va axloqiy kapital'), ('HEALTH', "Sog'lom hayot kapitali"), ('CIVIC', 'Fuqarolik kapitali')], max_length=32, unique=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('default_weight', models.DecimalField(decimal_places=3, default=1.0, max_digits=4)),
            ],
            options={
                'db_table': 'taxonomy_capital_dimension',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='taxonomy.region')),
            ],
            options={
                'db_table': 'taxonomy_region',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='taxonomy.skillcategory')),
            ],
            options={
                'verbose_name_plural': 'skill categories',
                'db_table': 'taxonomy_skill_category',
                'ordering': ['order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='taxonomy.skillcategory')),
            ],
            options={
                'db_table': 'taxonomy_skill',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('demand_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=8)),
                ('median_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professions', to='taxonomy.skillcategory')),
            ],
            options={
                'db_table': 'taxonomy_profession',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='SkillDimension',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=3, default=1.0, max_digits=4)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='taxonomy.capitaldimension')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_links', to='taxonomy.skill')),
            ],
            options={
                'db_table': 'taxonomy_skill_dimension',
            },
        ),
        migrations.CreateModel(
            name='ProfessionSkill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement', models.CharField(choices=[('REQUIRED', 'Required'), ('PREFERRED', 'Preferred')], default='REQUIRED', max_length=12)),
                ('min_proficiency', models.PositiveSmallIntegerField(default=50)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='taxonomy.profession')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profession_links', to='taxonomy.skill')),
            ],
            options={
                'db_table': 'taxonomy_profession_skill',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['profession', 'requirement'], name='taxonomy_pr_profess_8b3940_idx')],
                'constraints': [models.UniqueConstraint(fields=('profession', 'skill'), name='uniq_profession_skill'), models.CheckConstraint(condition=models.Q(('min_proficiency__gte', 0), ('min_proficiency__lte', 100)), name='profession_skill_proficiency_range')],
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'is_active'], name='taxonomy_sk_categor_a39d94_idx'),
        ),
        migrations.AddConstraint(
            model_name='skilldimension',
            constraint=models.UniqueConstraint(fields=('skill', 'dimension'), name='uniq_skill_dimension'),
        ),
    ]
