# Generated by Django 5.2.17 on 2026-09-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='is_soft_skill',
            field=models.BooleanField(default=False),
        ),
    ]
