# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('horizon', models.CharField(choices=[('M3', '3 months'), ('Y1', '1 year'), ('Y3', '3 years')], default='M3', max_length=2)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACHIEVED', 'Achieved'), ('DROPPED', 'Dropped')], default='ACTIVE', max_length=8)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(choices=[('USER', 'User'), ('AI', 'AI generated'), ('MENTOR', 'Mentor')], default='USER', max_length=8)),
                ('target_profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='taxonomy.profession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'idp_goal',
                'ordering': ['horizon', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, max_length=2000)),
                ('period_days', models.PositiveSmallIntegerField(default=90)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('source', models.CharField(choices=[('USER', 'User'), ('AI', 'AI generated'), ('MENTOR', 'Mentor')], default='AI', max_length=8)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('ai_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='ai.airequestlog')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='idp.goal')),
            ],
            options={
                'db_table': 'idp_development_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('MISSED', 'Missed')], default='PENDING', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='idp.developmentplan')),
            ],
            options={
                'db_table': 'idp_milestone',
                'ordering': ['order', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('type', models.CharField(choices=[('COURSE', 'Take a course'), ('LESSON', 'Complete a lesson'), ('TEST', 'Pass a test'), ('PROJECT', 'Build a project'), ('APPLICATION', 'Apply to a vacancy'), ('MENTOR_SESSION', 'Book a mentor session'), ('PROFILE', 'Complete your profile'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=16)),
                ('ref_type', models.CharField(blank=True, max_length=40)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('SKIPPED', 'Skipped')], default='TODO', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(choices=[('USER', 'User'), ('AI', 'AI generated'), ('MENTOR', 'Mentor')], default='AI', max_length=8)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='idp.milestone')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='idp.developmentplan')),
                ('related_skills', models.ManyToManyField(blank=True, related_name='tasks', to='taxonomy.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'idp_task',
                'ordering': ['due_date', 'order', '-priority'],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='idp_goal_user_id_556837_idx'),
        ),
        migrations.AddIndex(
            model_name='developmentplan',
            index=models.Index(fields=['user', 'status'], name='idp_develop_user_id_465e35_idx'),
        ),
        migrations.AddConstraint(
            model_name='developmentplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user',), name='one_active_plan_per_user'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status', 'due_date'], name='idp_task_user_id_95d283_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['plan', 'status'], name='idp_task_plan_id_8f4b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['ref_type', 'ref_id'], name='idp_task_ref_typ_dde539_idx'),
        ),
    ]
