# Generated by Django 5.2.6 on 2026-08-24 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStreak',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_days', models.PositiveIntegerField(default=0)),
                ('longest_days', models.PositiveIntegerField(default=0)),
                ('last_active_on', models.DateField(blank=True, db_index=True, null=True)),
                ('actions_today', models.PositiveSmallIntegerField(default=0)),
                ('counted_on', models.DateField(blank=True, null=True)),
                ('daily_goal', models.PositiveSmallIntegerField(default=1)),
                ('total_active_days', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'idp_learning_streak',
            },
        ),
    ]
