# Generated by Django 5.2.17 on 2026-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0003_plan_text_as_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentplan',
            name='source',
            field=models.CharField(choices=[('USER', 'User'), ('AI', 'AI generated')], default='AI', max_length=8),
        ),
        migrations.AlterField(
            model_name='goal',
            name='source',
            field=models.CharField(choices=[('USER', 'User'), ('AI', 'AI generated')], default='USER', max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('USER', 'User'), ('AI', 'AI generated')], default='AI', max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('COURSE', 'Take a course'), ('LESSON', 'Complete a lesson'), ('TEST', 'Pass a test'), ('PROJECT', 'Build a project'), ('APPLICATION', 'Apply to a vacancy'), ('PROFILE', 'Complete your profile'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=16),
        ),
    ]
