# Generated by Django 5.2.6 on 2026-08-19 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TASK_DUE', 'Task due'), ('TASK_OVERDUE', 'Task overdue'), ('PLAN_READY', 'Development plan ready'), ('COURSE_COMPLETED', 'Course completed'), ('TEST_GRADED', 'Test graded'), ('SKILL_VERIFIED', 'Skill verified'), ('NEW_MATCH', 'New matching vacancy'), ('APPLICATION_STATUS', 'Application status changed'), ('NEW_APPLICATION', 'New application received'), ('INTERVIEW_SCHEDULED', 'Interview scheduled'), ('MENTOR_REQUEST', 'Mentor session requested'), ('MENTOR_RESPONSE', 'Mentor responded'), ('MODERATION_RESULT', 'Moderation decision'), ('SYSTEM', 'System message')], max_length=24)),
                ('title_key', models.CharField(max_length=80)),
                ('body_key', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ref_type', models.CharField(blank=True, max_length=40)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('channel', models.CharField(choices=[('IN_APP', 'In app'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push'), ('TELEGRAM', 'Telegram')], default='IN_APP', max_length=10)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=8)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['type', '-created_at'], name='notificatio_type_36f2e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TASK_DUE', 'Task due'), ('TASK_OVERDUE', 'Task overdue'), ('PLAN_READY', 'Development plan ready'), ('COURSE_COMPLETED', 'Course completed'), ('TEST_GRADED', 'Test graded'), ('SKILL_VERIFIED', 'Skill verified'), ('NEW_MATCH', 'New matching vacancy'), ('APPLICATION_STATUS', 'Application status changed'), ('NEW_APPLICATION', 'New application received'), ('INTERVIEW_SCHEDULED', 'Interview scheduled'), ('MENTOR_REQUEST', 'Mentor session requested'), ('MENTOR_RESPONSE', 'Mentor responded'), ('MODERATION_RESULT', 'Moderation decision'), ('SYSTEM', 'System message')], max_length=24)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_preference',
                'constraints': [models.UniqueConstraint(fields=('user', 'type'), name='uniq_notification_preference')],
            },
        ),
    ]
