# Generated by Django 5.2.17 on 2026-09-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TASK_DUE', 'Task due'), ('TASK_OVERDUE', 'Task overdue'), ('PLAN_READY', 'Development plan ready'), ('COURSE_COMPLETED', 'Course completed'), ('TEST_GRADED', 'Test graded'), ('SKILL_VERIFIED', 'Skill verified'), ('NEW_MATCH', 'New matching vacancy'), ('APPLICATION_STATUS', 'Application status changed'), ('NEW_APPLICATION', 'New application received'), ('INTERVIEW_SCHEDULED', 'Interview scheduled'), ('MENTOR_REQUEST', 'Mentor session requested'), ('MENTOR_RESPONSE', 'Mentor responded'), ('MODERATION_RESULT', 'Moderation decision'), ('REVIEW_REQUEST', 'Asked for feedback on the platform'), ('SYSTEM', 'System message')], max_length=24),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='type',
            field=models.CharField(choices=[('TASK_DUE', 'Task due'), ('TASK_OVERDUE', 'Task overdue'), ('PLAN_READY', 'Development plan ready'), ('COURSE_COMPLETED', 'Course completed'), ('TEST_GRADED', 'Test graded'), ('SKILL_VERIFIED', 'Skill verified'), ('NEW_MATCH', 'New matching vacancy'), ('APPLICATION_STATUS', 'Application status changed'), ('NEW_APPLICATION', 'New application received'), ('INTERVIEW_SCHEDULED', 'Interview scheduled'), ('MENTOR_REQUEST', 'Mentor session requested'), ('MENTOR_RESPONSE', 'Mentor responded'), ('MODERATION_RESULT', 'Moderation decision'), ('REVIEW_REQUEST', 'Asked for feedback on the platform'), ('SYSTEM', 'System message')], max_length=24),
        ),
    ]
